### ISSUE TITLE
Login ssh keys can't be empty

### ISSUE THREAD

**Issue by nikohaap** [UpCloudLtd/terraform-provider-upcloud#47]
If there's a custom image in use there's no need for additional keys since those can be added by the packer. I wouldn't like to drop out the login since it's nice to have root passwords just in case 😄 
It seems that the Terraform plan is impossible to run successfully if the login's ssh key option is empty.

Actually I think it's by the design that it's not possible to manage ssh keys by that login option with the custom images? 

**Snippet from the server.tf file:** 
<pre>
  # Login details
  login {
    user              = "${var.user}"
    keys              = "${var.keys}" <-- In here it would be nice to have an empty value option
    create_password   = "${var.create_password}"
    password_delivery = "${var.password_delivery}"
  }
</pre>

I have used the custom connection block so  the solution has been to add the "terraform" user public key into that keys variable.

**Comment by PopoSensei** [comment]
Thanks for submitting the issue.

In the current Provider if the keys is defined we require it contains a string that is populated (so no empty strings), since the underlying program will define a ssh key to the server. So if the keys attribute is leaved completely out, there won't be any ssh keys defined by the Provider into the server.

So I would suggest leaving the keys out for those cases when you want servers with only login credentials, and defining keys when ssh-keys are the way to go.

It's probably not the answer you were looking for, but I hope I answered the question .

**Comment by PopoSensei** [comment]
Will now close this issue
