### ISSUE TITLE
How to get database user passwords out?

### ISSUE THREAD

**Issue by back-2-95** [UpCloudLtd/terraform-provider-upcloud#555]
I have challenging times to get out passwords when I create database users (MySQL).

I create users for every database like this using for_each:

```tf
resource "upcloud_managed_database_user" "default" {
  for_each       = toset(var.databases)
  service        = upcloud_managed_database_mysql.default.id
  username       = each.value
  authentication = "caching_sha2_password"
}
```

and my closest attempt to output passwords is this (but failing, I get only usernames and empty values for password):

```tf
output "database_user_passwords" {
  value = {
    for k, user in upcloud_managed_database_user.default : k => user.password
  }
}
```

**Comment by villevsv-upcloud** [comment]
Hello! Your configuration outputs following warning, because the password field is marked as sensitive in our provider:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Output refers to sensitive values
│ 
│   on main.tf line 33:
│   33: output "database_user_passwords" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
╵
```

This happens at least with these versions of Terraform client and UpCloud provider (`terraform -version`):

```
Terraform v1.8.4
on linux_amd64
+ provider registry.terraform.io/upcloudltd/upcloud v5.5.0
```

You can output the password directly to the Terraform output with `nonsensitive(user.password)` or, by using a more recommended technique, adding `sensitive = true` in the output block and running `terraform output -raw database_user_passwords` after apply.

More details can be found in this HashiCorp article: https://support.hashicorp.com/hc/en-us/articles/5175257151891-How-to-output-sensitive-data-with-Terraform

I will be closing this ticket as the provider works how it's intended and the question should be answered.
