### ISSUE TITLE
Provider v5.9.0 wants to remove attached networks from routers

### ISSUE THREAD

**Issue by kividiot** [UpCloudLtd/terraform-provider-upcloud#607]
Provider version: v.5.9.0
Opentofu version: 1.7 and 1.8

After upgrade to latest provider, it wants to remove all attached_networks on all routers.

The changes in the provider should remove the empty lines, but seems to only remove the non empty lines.

Running tofu plan
```
# upcloud_router.router will be updated in-place
  ~ resource "upcloud_router" "router" {
      ~ attached_networks = [
          - "network-1-id",
          - "network-2-id",
          - "network-3-id",
          - "network-4-id",
          - "network-5-id",
        ] -> (known after apply)
        id                = "router-id"
        name              = "router-name"
```

Running tofu state  show upcloud_router.router

```
# upcloud_router.router:
resource "upcloud_router" "router" {
    attached_networks = [
        "",
        "",
        "",
        "",
        "",
        "network-1-id",
        "network-2-id",
        "network-3-id",
        "network-4-id",
        "network-5-id",
    ]
    id                = "router-id"
    labels            = {}
    name              = "router-name"
    type              = "normal"
```

**Comment by kangasta** [comment]
The `attached_networks` field is computed based on the API response, so if there are no changes in the related network resources, the value should be the same also after apply even though it's unknown during the planning. The `attached_networks` is also a purely read-only field on router resource so this change would only be done to Terraform state.

We'll take a look on why those empty string are not included in the change listing 🤔

**Comment by kividiot** [comment]
So it should be OK to apply these changes?

**Comment by villevsv-upcloud** [comment]
Hello! Running apply command for the plan shown in the original post will not detach any networks from the router, so it is OK to do this.

Reasoning here is that `upcloud_router` Terraform resource is not able to attach or detach networks from routers by design, and the field `attached_networks` is only informational for the user.

One thing to note is that the output of the `attached_networks` field can and should change after apply.

If the plan would notify that `upcloud_network` resources are to be updated in-place due to changes in the `router` field, then the underlying attachments could possibly change. But that doesn't seem to be case here based on the plan from the original post.

**Comment by kividiot** [comment]
Ok, then you can close this issue, as it's working as intended
