### ISSUE TITLE
Whenever I import a running upcloud_server instance, storage devices do not get imported

### ISSUE THREAD

**Issue by karvounis** [UpCloudLtd/terraform-provider-upcloud#72]
I am trying to import the current Upcloud infrastructure to a terraform state file. That server, webServerA, has 3 storage devices attached to it.
This is the terraform resource block for that upcloud_server
```
resource "upcloud_server" "webserver" {
  zone     = "nl-ams1"
  hostname = "webServerA"
}
```

I am executing `terraform import upcloud_server.webServerA <server_id>`.

It gets imported successfully however without the information regarding the storage devices and their backup rules.

`terraform state show upcloud_server.webServerA` output:

```
# upcloud_server.webServerA:
resource "upcloud_server" "webServerA" {
    cpu                  = 6
    hostname             = "webServerA"
    id                   = <server_id>
    ipv4_address         = <server_ip>
    ipv4_address_private = <<server_ip_private>
    mem                  = 8192
    title                = "webServerA (managed by terraform)"
    zone                 = "nl-ams1"
}
```

This is obviously not the correct resource.
 
Now the problem is that when I am trying to execute `terraform plan`, it tries to recreate the storage devices because they do not exist in the state file.

**Comment by kirksw** [comment]
I also had this issue, so I tried to import the storage separately using`terraform import upcloud_storage.upcloud01-ssd01 <ssd uuid>`

However this doesn't matter as as terraform plan fails with `Error: insufficient items for attribute "storage_devices"; must have at least 1`.

It really seems like upcloud has the worst support for both ansible and terraform.

**Comment by PopoSensei** [comment]
Hello,

We have updated Terraform Provider and the underlying Go-Api, and using the latest master branch version, I got the imports working. The storages will need to be imported separately, since in the implementation they are defined as separate resource blocks. This allows the user to modify the size of the main system storage. It's not the standard way of doing things which is partly why Terraform doesn't work with it.

The server will be destroyed and recreated in the process, but the storages will remain unchanged.

These are the steps I took:

1. Create a server with 2 storages trough hub
2. Create a terraform file like this one:
```

# testimport server <PASTED UUID OF SERVER>
resource "upcloud_server" "testimport" {
  zone     = "de-fra1"
  hostname = "testimport"
}
# testimport Device 1 <PASTED UUID OF STORAGE 1>
resource "upcloud_storage" "import_storage_1" {
    title = "testimport Device 2"
    zone  = "de-fra1"
}
# testimport Device 2 <PASTED UUID OF STORAGE 1>
resource "upcloud_storage" "import_storage_2" {
    title = "testimport Device 2"
    zone  = "de-fra1"
}
```
3. Import server
`$ terraform import upcloud_server.testimport <PASTED UUID OF SERVER>`
4. Look at the state and paste content in the file replacing testimport resource, while making sure, that the UUID matches the one I have
`$ terraform state show upcloud_server.testimport`
```
# upcloud_server.testimport:
resource "upcloud_server" "testimport" {
    cpu      = 1
    hostname = "testimport"
    id       = <PASTED UUID OF SERVER>
    mem      = 1024
    title    = "testimport"
    zone     = "de-fra1"

    network_interface {
        bootable            = false
        ip_address          = <Generated Address>
        ip_address_family   = "IPv4"
        ip_address_floating = false
        mac_address         = <Generated Address>
        network             = <NETWORK UUID>
        source_ip_filtering = true
        type                = "public"
    }
    network_interface {
        bootable            = false
        ip_address          = <Generated Address>
        ip_address_family   = "IPv4"
        ip_address_floating = false
        mac_address         = <Generated Address>
        network             = <NETWORK UUID>
        source_ip_filtering = true
        type                = "utility"
    }
    network_interface {
        bootable            = false
        ip_address          =<Generated Address>
        ip_address_family   = "IPv6"
        ip_address_floating = false
        mac_address         = <Generated Address>
        network             = <NETWORK UUID>
        source_ip_filtering = true
        type                = "public"
    }
}
```
5. Took out server id and title from server and made network interfaces shorted in the pasted resource
```
# upcloud_server.testimport:
resource "upcloud_server" "testimport" {
    cpu      = 1
    hostname = "testimport"
    id       = <PASTED UUID OF SERVER>
    mem      = 1024
    title    = "testimport"
    zone     = "de-fra1"

    network_interface {
        type                = "public"
    }
    network_interface {
        type                = "utility"
    }
    network_interface {
        ip_address_family   = "IPv6"
        type                = "public"
    }
}
```
6. Repeat process for BOTH storages, except those only have the UUID of storage that needs to be removed from the actual terraform file.
7. Add Storage devices to the server resource, with attach action, since those storages will not be destroyed in the process
```
    storage_devices {
      action  = "attach"
      size    = upcloud_storage.import_storage_1.size
      storage = upcloud_storage.import_storage_1.id
    }
    storage_devices {
      action  = "attach"
      size    = upcloud_storage.import_storage_2.size
      storage = upcloud_storage.import_storage_2.id
    }
```
8. `$ terraform plan` and make sure that the server is the only resource destroyed and created
9. Apply and profit

Hope this process helps. And Let me know if this doesn't work for you as it did for me.

**Comment by PopoSensei** [comment]
Will now close this issue, since the importing works as described above.
